import { PATHFINDING_COSTS } from '../pathfindng';

export interface GroundCost {
  VERY_SLOW: number;
  SLOW: number;
  NORMAL: number;
  FAST: number;
  VERY_FAST: number;
}

export const GROUND_COST: GroundCost = {
  VERY_SLOW: PATHFINDING_COSTS.GROUND_VERY_SLOW,
  SLOW: PATHFINDING_COSTS.GROUND_SLOW,
  NORMAL: PATHFINDING_COSTS.GROUND_NORMAL,
  FAST: PATHFINDING_COSTS.GROUND_FAST,
  VERY_FAST: PATHFINDING_COSTS.GROUND_VERY_FAST
};
